[package]
name = "wlgif"
version = "0.2.0"
edition = "2024"
description = "Lightweight screen recorder for Wayland that captures regions as GIFs"
homepage = "https://github.com/doprz/wlgif"
repository = "https://github.com/doprz/wlgif"
readme = "README.md"
license = "MIT"
keywords = ["wayland", "gif", "screen-recording", "wlroots", "linux"]
categories = ["command-line-utilities", "multimedia"]
exclude = [
    "nix/",
    "*.nix",
    "flake.lock",
    ".editorconfig",
    "justfile",
    ".envrc",
    ".github"
]

[dependencies]
anyhow = "1.0.100"
ashpd = "0.12.0"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
const_format = "0.2.35"
ctrlc = "3.5.1"
gstreamer = "0.24.4"
libc = "0.2.178"
tempfile = "3.24.0"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
which = "8.0.0"
gtk = { package = "gtk4", version = "0.11" }
gtk4-layer-shell = "0.8"

[profile.release]
lto = true
strip = true
codegen-units = 1
